# This workflow makes pushing the client and server directories to their respective subtree branches
# an automatic procees triggered by pushing to the main branch
name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: deploy frontend
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: client
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: deploy backend
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: socket-server
        FOLDER: server
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
